name: base
channels:
  - conda-forge
dependencies:
  - boltons=23.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.0
  - colorama=0.4.6
  - conda=23.7.4
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.4
  - fmt=10.1.1
  - icu=73.2
  - idna=3.4
  - jsonpatch=1.33
  - jsonpointer=2.4
  - krb5=1.21.2
  - libarchive=3.6.2
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcurl=8.3.0
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.52.0
  - libsolv=0.7.25
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.1
  - ncurses=6.4
  - openssl=3.1.3
  - packaging=23.2
  - pip=23.2.1
  - pluggy=1.3.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.6
  - python_abi=3.11
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.17.35
  - ruamel.yaml.clib=0.2.7
  - ruamel_yaml=0.15.80
  - setuptools=68.2.2
  - tk=8.6.13
  - toolz=0.12.0
  - tqdm=4.66.1
  - truststore=0.8.0
  - tzdata=2023c
  - urllib3=2.0.6
  - wheel=0.41.2
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zstandard=0.21.0
  - zstd=1.5.5
