name: base
channels:
  - conda-forge
dependencies:
  - archspec=0.2.5
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - conda=25.1.1
  - conda-libmamba-solver=25.1.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - distro=1.9.0
  - fmt=11.1.4
  - frozendict=2.4.6
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - krb5=1.21.3
  - libarchive=3.7.7
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libiconv=1.18
  - liblzma=5.6.4
  - libmamba=2.0.7
  - libmambapy=2.0.7
  - libnghttp2=1.64.0
  - libsolv=0.7.30
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libxml2=2.13.6
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.0.7
  - menuinst=2.2.0
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - openssl=3.4.1
  - packaging=24.2
  - pip=25.0.1
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.9
  - python_abi=3.12
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.8.2
  - simdjson=3.12.2
  - spdlog=1.15.1
  - tk=8.6.13
  - tqdm=4.67.1
  - truststore=0.10.1
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - yaml-cpp=0.8.0
  - zstandard=0.23.0
  - zstd=1.5.6

