name: base
channels:
  - conda-forge
dependencies:
  - archspec=0.2.3
  - boltons=23.1.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=24.1.2
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=42.0.5
  - distro=1.9.0
  - fmt=10.2.1
  - icu=73.2
  - idna=3.6
  - jsonpatch=1.33
  - jsonpointer=2.4
  - krb5=1.21.2
  - libarchive=3.7.2
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.5.7
  - libmambapy=1.5.7
  - libnghttp2=1.58.0
  - libsolv=0.7.28
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libxml2=2.12.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.7
  - menuinst=2.0.2
  - ncurses=6.4
  - openssl=3.2.1
  - packaging=23.2
  - pip=24.0
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.11.8
  - python_abi=3.11
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.15.80
  - setuptools=69.1.1
  - tk=8.6.13
  - toolz=0.12.1
  - tqdm=4.66.2
  - truststore=0.8.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.42.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zstandard=0.22.0
  - zstd=1.5.5
