name: base
channels:
  - conda-forge
dependencies:
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - conda=23.5.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - cryptography=41.0.1
  - fmt=9.1.0
  - icu=72.1
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.0
  - krb5=1.20.1
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.4.4
  - libmambapy=1.4.4
  - libnghttp2=1.52.0
  - libsolv=0.7.24
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libxml2=2.11.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.4
  - ncurses=6.4
  - openssl=3.1.1
  - packaging=23.1
  - pip=23.1.2
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.4
  - python_abi=3.11
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - ruamel_yaml=0.15.80
  - setuptools=67.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=2.0.3
  - wheel=0.40.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zstandard=0.19.0
  - zstd=1.5.2
