name: base
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - archspec=0.2.3
  - backports=1.0
  - backports.tarfile=1.0.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cachy=0.3.0
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-default-group=1.2.4
  - clikit=0.6.2
  - colorama=0.4.6
  - conda=24.5.0
  - conda-libmamba-solver=24.1.0
  - conda-lock=2.5.7
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - crashtest=0.4.1
  - distlib=0.3.8
  - distro=1.9.0
  - ensureconda=1.4.4
  - filelock=3.15.4
  - fmt=10.2.1
  - frozendict=2.4.4
  - gitdb=4.0.11
  - gitpython=3.1.43
  - html5lib=1.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.2.1
  - importlib_metadata=7.2.1
  - importlib_resources=6.4.0
  - jaraco.classes=3.4.0
  - jaraco.context=5.3.0
  - jaraco.functools=4.0.0
  - jinja2=3.1.4
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.2.1
  - krb5=1.21.2
  - libarchive=3.7.4
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libsolv=0.7.29
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markupsafe=2.1.5
  - menuinst=2.1.1
  - more-itertools=10.3.0
  - msgpack-python=1.0.8
  - ncurses=6.5
  - openssl=3.3.1
  - packaging=24.1
  - pastel=0.2.1
  - pip=24.0
  - pkginfo=1.11.1
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydantic=2.7.4
  - pydantic-core=2.18.4
  - pylev=1.4.0
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pyyaml=6.0.1
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=70.1.0
  - six=1.16.0
  - smmap=5.0.0
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.12.5
  - toolz=0.12.1
  - tqdm=4.66.4
  - truststore=0.8.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=1.26.19
  - virtualenv=20.26.3
  - webencodings=0.5.1
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zipp=3.19.2
  - zstandard=0.22.0
  - zstd=1.5.6
